const state={environment:'TESTNET',csrf:'',status:null,market:{},side:'LONG',orders:[],pendingOrder:null,portfolio:null,environmentEpoch:0};
const $=id=>document.getElementById(id);
const money=v=>Number.isFinite(v)?new Intl.NumberFormat('en-US',{minimumFractionDigits:2,maximumFractionDigits:2}).format(v):'—';
const duration=ms=>{const s=Math.floor((ms||0)/1000);return [Math.floor(s/3600),Math.floor(s%3600/60),s%60].map(v=>String(v).padStart(2,'0')).join(':')};
async function api(path,options={}){options.headers={...(options.headers||{}),'Content-Type':'application/json'};if(options.method&&options.method!=='GET')options.headers['X-CSRF-Token']=state.csrf;const response=await fetch(path,options);const data=await response.json().catch(()=>({error:'Invalid server response'}));if(!response.ok)throw new Error(data.error||`HTTP ${response.status}`);return data}
function toast(message,error=false){const node=$('toast');node.textContent=message;node.className=error?'show error':'show';setTimeout(()=>node.className='',2800)}
function setText(id,value){const node=$(id);if(node)node.textContent=value}
function renderMarket(market){state.market=market||{};setText('headerPrice',market.futures_price?`$${money(market.futures_price)}`:'—');setText('futuresPrice',market.futures_price?`$${money(market.futures_price)}`:'—');setText('spotPrice',market.spot_price?`$${money(market.spot_price)}`:'—');setText('markPrice',market.mark_price?`$${money(market.mark_price)}`:'—');setText('premiumValue',Number.isFinite(market.premium)?`Premium ${(market.premium*100).toFixed(4)}%`:'Premium —');setText('updatedAt',market.updated_at?`Updated ${new Date(market.updated_at).toLocaleTimeString()}`:'Awaiting market data');$('connectionDot').classList.toggle('connected',!!market.connected);setText('connectionText',market.connected?'CONNECTED':'DEGRADED');setText('gateMarket',market.connected?'CONNECTED':'DEGRADED');recalculate()}
function renderWarmup(w){const required=w.required_ms||14400000,available=w.available_ms||0,current=w.source==='traderui_live_runtime'||w.source==='readiness_service',pct=current?Math.min(100,available/required*100):0,previous=w.historical_capture?.available_ms||0,bootstrap=w.bootstrap_state||'IDLE';setText('warmupTime',current?`${duration(available)} / ${duration(required)}`:'NOT READY');setText('warmupMissing',duration(w.missing_ms));setText('warmupPercent',current?`${pct.toFixed(1)}%`:'NOT READY');$('warmupBar').style.width=`${pct}%`;setText('warmupStatus',w.status||'IDLE');$('warmupStatus').className=`status ${w.ready?'ok':'warning'}`;setText('gateWarmup',w.ready?'READY':`${w.status||'IDLE'} / NOT READY`);setText('warmupExplanation',`Live Feature input: ${w.input_connected?'CONNECTED':'NOT CONNECTED'}. Bootstrap: ${bootstrap}. Futures history: ${duration(w.futures_history_ms||0)}. Spot history: ${duration(w.spot_history_ms||0)}. Stabilization: ${duration(w.stabilization_ms||0)} / ${duration(w.stabilization_target_ms||0)}. Elapsed: ${!!w.stabilization_elapsed}. Ready: ${!!w.ready}.`);setText('systemWarmup',`Live Feature input ${w.input_connected?'CONNECTED':'NOT CONNECTED'} · Bootstrap ${bootstrap} · Engine ${w.status||'IDLE'} · Futures history ${duration(w.futures_history_ms||0)} · Spot history ${duration(w.spot_history_ms||0)} · Stabilization ${duration(w.stabilization_ms||0)} / ${duration(w.stabilization_target_ms||0)} · Elapsed ${!!w.stabilization_elapsed} · Ready ${!!w.ready} · Futures canonical bars ${w.futures_bars||0} · Spot canonical bars ${w.spot_bars||0} · Futures gaps ${w.futures_gaps||0} · Spot gaps ${w.spot_gaps||0} · Blocker ${w.bootstrap_blocker||'NONE'}${w.blocker_source?` source=${w.blocker_source}`:''} · Last event ${w.last_event_time_ms?new Date(w.last_event_time_ms).toLocaleString():'NONE'} · Last checkpoint ${w.last_checkpoint_ms?new Date(w.last_checkpoint_ms).toLocaleString():'NONE'}`)}
function credentialReady(){const c=state.status?.credentials||{};return state.environment==='TESTNET'?c.testnet_api_key_present&&c.testnet_secret_present:c.mainnet_api_key_present&&c.mainnet_secret_present}
function renderEnvironment(){const main=state.environment==='MAINNET';document.querySelectorAll('.env-button').forEach(b=>b.classList.toggle('active',b.dataset.env===state.environment));const badge=$('environmentBadge');badge.textContent=main?'MAINNET DISABLED':'BINANCE DEMO';badge.className=`badge ${main?'live':'test'}`;setText('orderEnvironment',main?'MAINNET':'BINANCE DEMO');setText('portfolioEnvironment',main?'MAINNET':'BINANCE DEMO');setText('gateCredentials',credentialReady()?'CONFIGURED':'MISSING');$('reviewOrder').textContent=`REVIEW ${state.side} ORDER`;document.body.classList.toggle('mainnet',main)}
const escapeHTML=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function renderPortfolio(data){state.portfolio=data;setText('portfolioStatus',data.portfolio_summary?.status||'TOTAL VALUE UNAVAILABLE');setText('portfolioTotal',data.portfolio_summary?.total_usdt==null?'TOTAL VALUE UNAVAILABLE':`${money(data.portfolio_summary.total_usdt)} USDT`);setText('spotStatus',data.spot?.status||'UNAVAILABLE');setText('dashboardSpotStatus',data.spot?.status||'UNAVAILABLE');setText('futuresStatus',data.futures?.status||'NOT CONNECTED');const assets=(data.spot?.assets||[]).filter(a=>$('showZeroAssets').checked||Number(a.total)!==0);$('spotAssetsBody').innerHTML=data.spot?.status!=='READY'?'<tr><td colspan="5">SPOT ACCOUNT NOT AVAILABLE</td></tr>':assets.length?assets.map(a=>`<tr><td>${escapeHTML(a.asset)}</td><td>${money(a.free)}</td><td>${money(a.locked)}</td><td>${money(a.total)}</td><td>${a.usdt_value==null?'—':money(a.usdt_value)}</td></tr>`).join(''):'<tr><td colspan="5">NO SPOT ASSETS TO DISPLAY</td></tr>';const wallet=data.futures?.wallet_assets?.[0]?.balance;$('futuresWallet').innerHTML=wallet?`<div><span>Wallet Balance</span><b>${money(wallet.wallet_balance_usdt)} USDT</b></div><div><span>Available</span><b>${money(wallet.available_balance_usdt)} USDT</b></div><div><span>Margin Balance</span><b>${money(wallet.margin_balance_usdt)} USDT</b></div><div><span>Used Margin</span><b>${money(wallet.used_margin_usdt)} USDT</b></div><div><span>Unrealized PnL</span><b>${money(wallet.unrealized_pnl_usdt)} USDT</b></div>`:'NOT CONNECTED';const positions=data.futures?.positions||[];$('futuresPositionsBody').innerHTML=positions.length?positions.map(p=>`<tr><td>${escapeHTML(p.symbol)}</td><td>${escapeHTML(p.side)}</td><td>${money(p.quantity_btc)}</td><td>${money(p.position_notional_usdt)}</td><td>${money(p.entry_price)}</td><td>${money(p.mark_price)}</td><td>${money(p.unrealized_pnl_usdt)}</td><td>${money(p.roe_percent)}%</td><td>${p.leverage}x</td><td>${money(p.margin_usdt)}</td><td>${money(p.liquidation_price)}</td></tr>`).join(''):'<tr><td colspan="11">NO OPEN FUTURES POSITION</td></tr>'}
function renderAccount(data){const a=data.account||{};setText('accountState',a.connected?'CONNECTED':'NOT CONNECTED');$('accountState').className=`status ${a.connected?'ok':'muted'}`;setText('walletBalance',a.connected?`${money(a.wallet_balance_usdt)} USDT`:'ACCOUNT NOT CONNECTED');setText('availableBalance',a.connected?`${money(a.available_balance_usdt)} USDT`:'—');setText('marginBalance',a.connected?`${money(a.margin_balance_usdt)} USDT`:'—');setText('usedMargin',a.connected?`${money(a.used_margin_usdt)} USDT`:'—');setText('unrealizedPnl',a.connected?`${money(a.unrealized_pnl_usdt)} USDT`:'—')}
function renderPositions(data){const p=data.positions?.[0];$('positionEmpty').classList.toggle('hidden',!!p);$('positionDetail').classList.toggle('hidden',!p);$('closePosition').disabled=!p;if(!p)return;$('positionDetail').innerHTML=`<div class="stat-list"><div><span>Side</span><b>${p.side}</b></div><div><span>Quantity</span><b>${p.quantity_btc} BTC</b></div><div><span>Entry</span><b>$${money(p.entry_price)}</b></div><div><span>Mark</span><b>$${money(p.mark_price)}</b></div><div><span>Notional</span><b>${money(p.position_notional_usdt)} USDT</b></div><div><span>Leverage</span><b>${p.leverage}x</b></div><div><span>TP</span><b>${p.take_profit?'$'+money(p.take_profit):'—'}</b></div><div><span>SL</span><b>${p.stop_loss?'$'+money(p.stop_loss):'—'}</b></div></div>`}
function renderOrders(data){state.orders=data.orders||[];$('ordersBody').innerHTML=state.orders.length?state.orders.map(o=>`<tr><td>${new Date(o.time).toLocaleTimeString()}</td><td>${o.environment}</td><td>${o.symbol}</td><td>${o.side}</td><td>${o.order_type}${o.protective?' · '+o.protective:''}</td><td>${o.quantity_btc}</td><td>${money(o.price)}</td><td>${o.status}</td><td><code>${o.client_order_id}</code></td></tr>`).join(''):'<tr><td colspan="9" class="table-empty">NO ORDERS IN THIS ENVIRONMENT</td></tr>'}
function renderCredentials(){const c=state.status?.credentials||{},items=[['TESTNET API KEY',c.testnet_api_key_present],['TESTNET SECRET',c.testnet_secret_present],['MAINNET API KEY',c.mainnet_api_key_present],['MAINNET SECRET',c.mainnet_secret_present]];$('credentialList').innerHTML=items.map(([n,v])=>`<div><span>${n}</span><b style="color:${v?'var(--green)':'var(--amber)'}">${v?'CONFIGURED':'MISSING'}</b></div>`).join('')}
async function refreshEnvironment(){
  const env=state.environment,epoch=state.environmentEpoch;
  try{
    const q=`?environment=${env}`;
    const [portfolio,account,positions,orders,auto]=await Promise.all([api('/api/portfolio'+q),api('/api/account'+q),api('/api/positions'+q),api('/api/orders'+q),api('/api/auto-trading'+q)]);
    if(epoch!==state.environmentEpoch)return;
    renderPortfolio(portfolio);renderAccount(account);renderPositions(positions);renderOrders(orders);
    const ready=auto.readiness||{},blockers=auto.blockers||[];
    setText('gateAccount',ready.account?'CONNECTED':'NOT CONNECTED');setText('gateBroker',ready.broker?'READY':'NOT READY');setText('gatePosition',ready.position||'UNKNOWN');setText('gateOrders',ready.orders_enabled?'YES':'NO');
    setText('gateOverall',ready.overall?'READY':`BLOCKED · ${ready.blocked_reason||'UNKNOWN'}`);
    const blockerText=blockers.map(b=>`${b.code} · Since ${new Date(b.since).toLocaleString()} · ${b.description}`).join('\n')||'NO_BLOCKERS';
    setText('entryBlockers',blockerText);setText('systemBlockers',blockerText);
    const killed=blockers.find(b=>b.code==='KILL_SWITCH_ACTIVE');setText('killSwitchState',killed?`Kill switch: ACTIVE · Since ${new Date(killed.since).toLocaleString()}`:'Kill switch: INACTIVE');
    setText('autoStatus',auto.state||'STOPPED');setText('autoPanelStatus',auto.state||'STOPPED');$('autoPanelStatus').className=`status ${auto.running?'ok':'muted'}`;
    setText('currentSignal',auto.signal||'NOT_READY');setText('signalValue',`Signal · ${auto.signal||'NOT_READY'}`);
    setText('candidateScores',auto.last_result?.scores?.map(x=>`${x.candidate_id} ${x.side} · p=${x.classification_probability.toFixed(4)} / ${x.classification_threshold.toFixed(4)} · r=${x.predicted_return.toFixed(6)} / ${x.regression_threshold.toFixed(6)} · ${x.pass?'PASS':'FAIL'}`).join('\n')||'No eligible live decision.');
    const intent=auto.last_result?.proposed_trade;setText('proposedTrade',intent?`${intent.side} ${intent.quantity_btc.toFixed(6)} BTC · ${money(intent.notional_usdt)} USDT · ${intent.leverage}x · TP ${money(intent.tp_price)} · SL ${money(intent.sl_price)} · RECORD ONLY`:'No proposed trade.');
  }catch(e){if(epoch===state.environmentEpoch)toast(e.message,true)}
}
async function initial(){try{state.status=await api('/api/status');state.csrf=state.status.csrf_token;renderMarket(state.status.market);renderWarmup(state.status.warmup);renderEnvironment();renderCredentials();const models=await api('/api/models');$('modelSelect').innerHTML=models.filter(m=>m.status==='FROZEN').map(m=>`<option value="${escapeHTML(m.id)}">${escapeHTML(m.name)}</option>`).join('');await refreshEnvironment();await refreshSystem();connectWS();setInterval(async()=>{try{const status=await api('/api/status');renderWarmup(status.warmup);await refreshEnvironment();await refreshSystem()}catch(e){}},10000)}catch(e){toast(e.message,true)}}
async function refreshSystem(){try{const [system,logs]=await Promise.all([api('/api/system'),api('/api/logs')]);$('connectionList').innerHTML=Object.entries(system.connections).map(([k,v])=>`<div><span>${k.replaceAll('_',' ').toUpperCase()}</span><b>${v===true?'CONNECTED':v===false?'DISCONNECTED':escapeHTML(v)}</b></div>`).join('');const metricRows=Object.entries(system.metrics_sources||{}).map(([k,v])=>`<div><span>${escapeHTML(k.toUpperCase())}</span><strong>${escapeHTML(v.status)}${v.current_age_ms>=0?` (${duration(v.current_age_ms)})`:''}</strong></div>`).join('');$('sourceGrid').innerHTML=Object.entries(system.sources).map(([k,v])=>`<div><span>${escapeHTML(k.toUpperCase())}</span><strong>${escapeHTML(v)}</strong></div>`).join('')+metricRows;const blocker=system.auto_blocker||{};setText('systemTelemetry',`Started ${new Date(system.session_started_at).toLocaleString()} · Uptime ${duration(system.uptime_ms)}\nAuto blocker: ${blocker.code||'NONE'}${blocker.source?` source=${blocker.source}`:''}${blocker.since_ms?` since=${new Date(blocker.since_ms).toLocaleString()}`:''}\n`+Object.entries(system.counters||{}).map(([k,v])=>`${k}: ${v==null?'UNAVAILABLE':v}`).join('\n'));setText('systemLatency',Object.entries(system.latency||{}).map(([k,v])=>`${k}: ${typeof v==='object'?`n=${v.samples} p50=${v.p50.toFixed(2)} p95=${v.p95.toFixed(2)} p99=${v.p99.toFixed(2)}`:v}`).join('\n'));renderWarmup(system.warmup);$('logs').textContent=logs.logs?.join('\n')||'No operational events.'}catch(e){toast(e.message,true)}}
function connectWS(){const protocol=location.protocol==='https:'?'wss':'ws',ws=new WebSocket(`${protocol}://${location.host}/ws`);ws.onmessage=e=>{const msg=JSON.parse(e.data);if(msg.type==='market')renderMarket(msg.market);if(msg.type==='warmup')renderWarmup(msg.warmup)};ws.onclose=()=>setTimeout(connectWS,2000)}
function recalculate(){const margin=Number($('marginAmount').value)||0,leverage=Number($('leverage').value)||1,notional=margin*leverage,price=state.market.futures_price||0,qty=price?Math.floor(notional/price*1000)/1000:0;setText('estimatedNotional',`${money(notional)} USDT`);setText('estimatedQuantity',qty?`${qty.toFixed(3)} BTC`:'— BTC');const tp=Number($('tpValue').value)||0,sl=Number($('slValue').value)||0,d=state.side==='LONG'?1:-1;setText('tpEstimate',price?`Estimated price $${money(price*(1+d*tp/100))}`:'Estimated price —');setText('slEstimate',price?`Estimated price $${money(price*(1-d*sl/100))}`:'Estimated price —')}
function requestBody(){return{environment:state.environment,symbol:'BTCUSDT',side:state.side,order_type:'MARKET',margin_amount_usdt:Number($('marginAmount').value),leverage:Number($('leverage').value),take_profit:{enabled:$('tpEnabled').checked,mode:'PERCENT',value:Number($('tpValue').value)},stop_loss:{enabled:$('slEnabled').checked,mode:'PERCENT',value:Number($('slValue').value)},options:{},request_id:`ui-${state.environment.toLowerCase()}-${Date.now()}`,live_confirmation:$('liveConfirmation').value}}
document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.nav-item').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));$(`page-${b.dataset.page}`).classList.add('active');if(b.dataset.page==='system')refreshSystem()}));
document.querySelectorAll('.env-button').forEach(b=>b.addEventListener('click',async()=>{if(b.dataset.env===state.environment)return;document.querySelectorAll('.env-button').forEach(x=>x.disabled=true);state.environment=b.dataset.env;state.environmentEpoch++;state.portfolio=null;state.orders=[];renderEnvironment();['walletBalance','availableBalance','marginBalance','usedMargin','unrealizedPnl','accountState','portfolioTotal','portfolioStatus','spotStatus','dashboardSpotStatus','futuresStatus','gateAccount','gateBroker','gatePosition','gateOrders','gateOverall','autoStatus','autoPanelStatus','entryBlockers','systemBlockers','currentSignal','candidateScores','proposedTrade','killSwitchState'].forEach(id=>setText(id,'LOADING'));$('spotAssetsBody').innerHTML='';$('futuresWallet').textContent='LOADING';$('futuresPositionsBody').innerHTML='';$('ordersBody').innerHTML='';$('positionDetail').innerHTML='';await refreshEnvironment();document.querySelectorAll('.env-button').forEach(x=>x.disabled=false)}));
$('showZeroAssets').addEventListener('change',()=>state.portfolio&&state.portfolio.environment===state.environment&&renderPortfolio(state.portfolio));
document.querySelectorAll('.side-toggle button').forEach(b=>b.addEventListener('click',()=>{state.side=b.dataset.side;document.querySelectorAll('.side-toggle button').forEach(x=>x.classList.toggle('active',x===b));$('reviewOrder').textContent=`REVIEW ${state.side} ORDER`;$('page-trading').classList.toggle('short-mode',state.side==='SHORT');recalculate()}));
['marginAmount','leverage','tpValue','slValue'].forEach(id=>$(id).addEventListener('input',recalculate));$('leverageDown').onclick=()=>{$('leverage').value=Math.max(1,Number($('leverage').value)-1);recalculate()};$('leverageUp').onclick=()=>{$('leverage').value=Math.min(125,Number($('leverage').value)+1);recalculate()};
$('reviewOrder').onclick=()=>{const body=requestBody(),main=state.environment==='MAINNET';state.pendingOrder=body;$('modalEnvironment').textContent=main?'MAINNET DISABLED':'TESTNET ORDER';$('modalEnvironment').className=`badge ${main?'live':'test'}`;setText('modalTitle',`Review ${state.side} order`);setText('modalWarning',main?'MAINNET execution is disabled':'Binance Testnet / Demo virtual funds');$('liveConfirmWrap').classList.toggle('hidden',!main);$('modalSummary').innerHTML=`<div><span>Side</span><b>${state.side}</b></div><div><span>Margin</span><b>${money(body.margin_amount_usdt)} USDT</b></div><div><span>Notional</span><b>${money(body.margin_amount_usdt*body.leverage)} USDT</b></div><div><span>Leverage</span><b>${body.leverage}x</b></div><div><span>TP / SL</span><b>${body.take_profit.value}% / ${body.stop_loss.value}%</b></div>`;$('confirmationDialog').showModal()};
$('confirmOrder').onclick=async e=>{e.preventDefault();const button=$('confirmOrder');if(button.disabled||!state.pendingOrder)return;button.disabled=true;if(state.environment==='MAINNET')state.pendingOrder.live_confirmation=$('liveConfirmation').value;try{const result=await api('/api/manual-order',{method:'POST',body:JSON.stringify(state.pendingOrder)});$('confirmationDialog').close();toast(result.execution==='TESTNET LIVE ORDERS'?'Testnet order accepted':'Paper order accepted');await refreshEnvironment()}catch(err){toast(err.message,true)}finally{button.disabled=false}};
async function autoAction(path){try{const body=path.endsWith('/start')?{model_profile_id:$('modelSelect').value}:{};await api(`${path}?environment=${state.environment}`,{method:'POST',body:JSON.stringify(body)});toast('Control state updated');await refreshEnvironment()}catch(e){toast(e.message,true)}}
$('startAuto').onclick=()=>autoAction('/api/auto-trading/start');$('stopAuto').onclick=()=>autoAction('/api/auto-trading/stop');$('emergencyStop').onclick=()=>autoAction('/api/auto-trading/emergency-stop');$('closePosition').onclick=()=>autoAction('/api/position/close');
$('reloadCredentials').onclick=async()=>{try{const result=await api('/api/credentials/reload',{method:'POST',body:'{}'});state.status.credentials=result.credentials;renderCredentials();renderEnvironment();toast(result.active_session)}catch(e){toast(e.message,true)}};
initial();
