package mainfeature

const FeatureVersion = 1

// MainFeaturesV1 separates timestamp/reference metadata from normalized and
// observed model candidates. All fields use fixed snake_case Parquet names.
type MainFeaturesV1 struct {
	DecisionTimestampMs        int64   `parquet:"decision_timestamp_ms"`
	ReferenceClose             float64 `parquet:"reference_close"`
	BarLogReturn               float64 `parquet:"bar_log_return"`
	BarRange                   float64 `parquet:"bar_range"`
	BarVWAPDeviation           float64 `parquet:"bar_vwap_deviation"`
	RetLog1s                   float64 `parquet:"ret_log_1s"`
	RetLog3s                   float64 `parquet:"ret_log_3s"`
	RetLog5s                   float64 `parquet:"ret_log_5s"`
	RetLog10s                  float64 `parquet:"ret_log_10s"`
	RetLog30s                  float64 `parquet:"ret_log_30s"`
	RetLog60s                  float64 `parquet:"ret_log_60s"`
	RetLog180s                 float64 `parquet:"ret_log_180s"`
	RetLog300s                 float64 `parquet:"ret_log_300s"`
	RetLog900s                 float64 `parquet:"ret_log_900s"`
	RetLog1800s                float64 `parquet:"ret_log_1800s"`
	RetLog3600s                float64 `parquet:"ret_log_3600s"`
	RetLog14400s               float64 `parquet:"ret_log_14400s"`
	RangeWidth10s              float64 `parquet:"range_width_10s"`
	RangePosition10s           float64 `parquet:"range_position_10s"`
	RangeWidth30s              float64 `parquet:"range_width_30s"`
	RangePosition30s           float64 `parquet:"range_position_30s"`
	RangeWidth60s              float64 `parquet:"range_width_60s"`
	RangePosition60s           float64 `parquet:"range_position_60s"`
	RangeWidth300s             float64 `parquet:"range_width_300s"`
	RangePosition300s          float64 `parquet:"range_position_300s"`
	RangeWidth900s             float64 `parquet:"range_width_900s"`
	RangePosition900s          float64 `parquet:"range_position_900s"`
	RangeWidth3600s            float64 `parquet:"range_width_3600s"`
	RangePosition3600s         float64 `parquet:"range_position_3600s"`
	RangeWidth14400s           float64 `parquet:"range_width_14400s"`
	RangePosition14400s        float64 `parquet:"range_position_14400s"`
	RV10s                      float64 `parquet:"rv_10s"`
	RV30s                      float64 `parquet:"rv_30s"`
	RV60s                      float64 `parquet:"rv_60s"`
	RV300s                     float64 `parquet:"rv_300s"`
	RV900s                     float64 `parquet:"rv_900s"`
	RV3600s                    float64 `parquet:"rv_3600s"`
	RV14400s                   float64 `parquet:"rv_14400s"`
	BaseVolumeSum5s            float64 `parquet:"base_volume_sum_5s"`
	QuoteVolumeSum5s           float64 `parquet:"quote_volume_sum_5s"`
	AggTradeCountSum5s         float64 `parquet:"agg_trade_count_sum_5s"`
	BaseVolumeSum30s           float64 `parquet:"base_volume_sum_30s"`
	QuoteVolumeSum30s          float64 `parquet:"quote_volume_sum_30s"`
	AggTradeCountSum30s        float64 `parquet:"agg_trade_count_sum_30s"`
	BaseVolumeSum60s           float64 `parquet:"base_volume_sum_60s"`
	QuoteVolumeSum60s          float64 `parquet:"quote_volume_sum_60s"`
	AggTradeCountSum60s        float64 `parquet:"agg_trade_count_sum_60s"`
	BaseVolumeSum300s          float64 `parquet:"base_volume_sum_300s"`
	QuoteVolumeSum300s         float64 `parquet:"quote_volume_sum_300s"`
	AggTradeCountSum300s       float64 `parquet:"agg_trade_count_sum_300s"`
	BaseVolumeSum900s          float64 `parquet:"base_volume_sum_900s"`
	QuoteVolumeSum900s         float64 `parquet:"quote_volume_sum_900s"`
	AggTradeCountSum900s       float64 `parquet:"agg_trade_count_sum_900s"`
	TakerImbalance1s           float64 `parquet:"taker_imbalance_1s"`
	TakerImbalance5s           float64 `parquet:"taker_imbalance_5s"`
	TakerImbalance10s          float64 `parquet:"taker_imbalance_10s"`
	TakerImbalance30s          float64 `parquet:"taker_imbalance_30s"`
	TakerImbalance60s          float64 `parquet:"taker_imbalance_60s"`
	TakerImbalance300s         float64 `parquet:"taker_imbalance_300s"`
	TakerImbalance900s         float64 `parquet:"taker_imbalance_900s"`
	VWAPDeviation30s           float64 `parquet:"vwap_deviation_30s"`
	VWAPDeviation60s           float64 `parquet:"vwap_deviation_60s"`
	VWAPDeviation300s          float64 `parquet:"vwap_deviation_300s"`
	VWAPDeviation900s          float64 `parquet:"vwap_deviation_900s"`
	TradeIntensity5s           float64 `parquet:"trade_intensity_5s"`
	TradeIntensity30s          float64 `parquet:"trade_intensity_30s"`
	TradeIntensity60s          float64 `parquet:"trade_intensity_60s"`
	TradeIntensity300s         float64 `parquet:"trade_intensity_300s"`
	NoTradeRatio30s            float64 `parquet:"no_trade_ratio_30s"`
	NoTradeRatio60s            float64 `parquet:"no_trade_ratio_60s"`
	NoTradeRatio300s           float64 `parquet:"no_trade_ratio_300s"`
	NoTradeRatio900s           float64 `parquet:"no_trade_ratio_900s"`
	MomentumAccel5s            float64 `parquet:"momentum_accel_5s"`
	MomentumAccel30s           float64 `parquet:"momentum_accel_30s"`
	MomentumAccel60s           float64 `parquet:"momentum_accel_60s"`
	ImbalanceChange5s          float64 `parquet:"imbalance_change_5s"`
	ImbalanceChange30s         float64 `parquet:"imbalance_change_30s"`
	ImbalanceChange60s         float64 `parquet:"imbalance_change_60s"`
	VolumeRatio5s60s           float64 `parquet:"volume_ratio_5s_60s"`
	TradeIntensityRatio5s60s   float64 `parquet:"trade_intensity_ratio_5s_60s"`
	VolumeRatio30s300s         float64 `parquet:"volume_ratio_30s_300s"`
	TradeIntensityRatio30s300s float64 `parquet:"trade_intensity_ratio_30s_300s"`
}
